routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Auth::routes();

Route::resource('/employees', 'EmployeesController');

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    protected $table = 'employees';
    protected $fillable = ['name', 'email'];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EmployeesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Employee;
use Session;

class EmployeesController extends Controller
{
    public function __construct() {
        $this->middleware('auth');
    }

    public function index()
    {
        $employees = Employee::all()->sortByDesc('id');
        return view('employees.index')->withEmployees($employees);
    }

    public function create()
    {
        return view('employees.create');
    }

    public function store(Request $request)
    {
        $request->validate([
          'employeeName' => 'required',
          'employeeEmail' => 'required|email',
        ]);

        $employee = new Employee();
        $employee->name = $request->employeeName;
        $employee->email = $request->employeeEmail;

        if ($employee->save()) {
          Session::flash('success', 'O funcionário foi cadastrado com sucesso!');
        } else {
          Session::flash('failed', 'Ocorreu algum erro ao tentar cadastrar o funcionário, tente novamente.');
        }

        return redirect()->route('employees.index');
    }

    public function show($id)
    {
        $employee = Employee::find($id);
        return view('employees.show')->withEmployee($employee);
    }

    public function edit($id)
    {
        $employee = Employee::find($id);
        return view('employees.edit')->withEmployee($employee);
    }

    public function update(Request $request, $id)
    {
      $request->validate([
        'employeeName' => 'required',
        'employeeEmail' => 'required|email',
      ]);

      $employee = Employee::find($id);
      $employee->name = $request->employeeName;
      $employee->email = $request->employeeEmail;

      if ($employee->save()) {
        Session::flash('success', 'O funcionário foi editado com sucesso!');
      } else {
        Session::flash('failed', 'Ocorreu algum erro ao tentar editar o funcionário, tente novamente.');
      }

        return redirect()->route('employees.index');
    }

    public function destroy($id)
    {
        $employee = Employee::find($id);

        if ($employee->delete()) {
          Session::flash('success', 'O funcionário foi deletado com sucesso!');
        }

        return redirect()->route('employees.index');
    }
}

resources/views/employees/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Novo Funcionário</div>
                  <div class="panel-body">
                    @if($errors->any())
                      <div class="alert alert-danger">
                       @foreach ($errors->all() as $error)
                         * {{ $error }}<br>
                       @endforeach
                      </div>
                    @endif
                    <form action="{{ route('employees.store') }}" method="POST">
                      {!! csrf_field() !!}
                      <div class="form-group">
                        <label for="InputName">Nome</label>
                        <input class="form-control" type="text" name="employeeName">
                      </div>
                      <div class="form-group">
                        <label for="InputEmail">Email</label>
                        <input class="form-control" type="text" name="employeeEmail">
                      </div>
                      <button type="submit" class="btn btn-success btn-block">Cadastrar</button>
                      <a href="{{ route('employees.index') }}" class="btn btn-primary" style="margin-top: 10px;"><< Voltar</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/employees/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Editar Funcionário</div>
                  <div class="panel-body">
                    @if($errors->any())
                      <div class="alert alert-danger">
                       @foreach ($errors->all() as $error)
                         * {{ $error }}<br>
                       @endforeach
                      </div>
                    @endif
                    <form action="{{ route('employees.update', $employee->id) }}" method="POST">
                      {!! csrf_field() !!}
                      <input type="hidden" name="_method" value="PUT">
                      <div class="form-group">
                        <label for="InputName">Nome</label>
                        <input class="form-control" type="text" name="employeeName" value="{{ $employee->name }}">
                      </div>
                      <div class="form-group">
                        <label for="InputEmail">Email</label>
                        <input class="form-control" type="text" name="employeeEmail" value="{{ $employee->email }}">
                      </div>
                      <button type="submit" class="btn btn-success btn-block">Editar</button>
                      <a href="{{ route('employees.index') }}" class="btn btn-primary" style="margin-top: 10px;"><< Voltar</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/employees/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Gerenciamento de Funcionários</div>
                  <div class="panel-body">
                    @if (Session::has('success'))
                      <div class="alert alert-success">{{ Session::get('success') }}</div>
                    @elseif (Session::has('failed'))
                      <div class="alert alert-danger">{{ Session::get('failed') }}</div>
                    @endif
                    <a href="{{ route('employees.create') }}" class="btn btn-success" style="float: right; margin-bottom: 15px;">Novo Funcionário</a>
                    <hr style="clear: both;">
                    <table class="table table-striped">
                      <thead>
                        <tr>
                          <th>ID</th>
                          <th>Nome</th>
                          <th>Email</th>
                          <th>Ação</th>
                        </tr>
                      </thead>
                      <tbody>
                          @foreach ($employees as $employee)
                            <tr>
                              <th scope="row">{{ $employee->id }}</th>
                              <td>{{ $employee->name }}</td>
                              <td>{{ $employee->email }}</td>
                              <td>
                                <a href="{{ route('employees.show', $employee->id) }}" class="btn btn-info">Visualizar</a>
                                <a href="{{ route('employees.edit', $employee->id) }}" class="btn btn-info">Editar</a>
                                <form style="display: inline-block;" action="{{ route('employees.destroy', $employee->id) }}" method="POST">
                                   {{ csrf_field() }}
                                   <input type="hidden" name="_method" value="DELETE">
                                   <button type="submit" class="btn btn-danger">Excluir</a>
                                </form>
                              </td>
                            </tr>
                          @endforeach
                      </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/employees/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Informações do Funcionário</div>
                  <div class="panel-body">
                    <table class="table table-striped">
                      <tbody>
                          <tr>
                            <th>ID:</th>
                            <td>{{ $employee->id }}</td>
                          </tr>
                          <tr>
                            <th>Nome:</th>
                            <td>{{ $employee->name }}</td>
                          </tr>
                          <tr>
                            <th>Email:</th>
                            <td>{{ $employee->email }}</td>
                          </tr>
                      </tbody>
                    </table>
                    <a href="{{ route('employees.index') }}" class="btn btn-primary"><< Voltar</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Página Inicial</div>
                    <div class="panel-body">
                        Bem Vindo!
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="{{ route('employees.index') }}">Gerenciamento de Funcionários</a></li>
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Sair
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>